#!/bin/bash
# Copyright © 2017 Martin Ueding <dev@martin-ueding.de>

# This integration test computes a large number of contractions on a 4^4 test
# lattice and compares the data to some reference result.

set -e
set -u
set -x

"$1/contract" -i test_all.ini

tree

for path in correlators-20171113/*.h5; do
    basename="${path##*/}"

    h5diff "$path" "correlators/$basename"
done
