#!/bin/bash

set -e
set -u

tmp="$(mktemp)"

good=( )
bad=( )

for path in correlators-reference/*.h5; do
    basename="${path##*/}"

    echo "Checking $basename …"

    target="$path"
    actual="correlators/$basename"

    if ! h5diff -r -d 1e-12 "$target" "$actual" &> "$tmp"; then
      cat "$tmp"
      bad=( "${bad[@]}" "$basename" )
    else
      good=( "${good[@]}" "$basename" )
    fi
done

rm -f -- "$tmp"

echo -e "\nSummary\n"
echo -e "No differences found in:\n"
for path in "${good[@]}"; do
  echo "  - $path"
done

echo -e "\nDifferences found in:\n"
for path in "${bad[@]}"; do
  echo "  - $path"
done

if [[ ${bad[@]} > 0 ]]; then
  exit 1
fi
