#!/bin/bash
# Copyright © 2017-2018 Martin Ueding <dev@martin-ueding.de>

# This integration test computes a large number of contractions on a 4^4 test
# lattice and compares the data to some reference result.

set -e
set -u
set -x

# Delete the old files. In case they care not there, the glob is not matched and that file
# cannot be found. Ignore that error/
rm correlators/*.h5 || true

# Copy incomplete correlators to the output directoru. The code should now just append to
# the existing file.
cp correlators-20180312-incomplete/*.h5 correlators/

"$1/contract" -i test_all.ini

./compare
