#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import os
import re
import shutil

import h5py


def handle_h5(path):
    f = h5py.File(path, 'r+')

    for dataset in f.keys():
        print(dataset)
        words = dataset.split('_')
        if '+' not in words[0]:
            continue

        words[0] = words[0].replace('+', 'c')
        new_dataset = '_'.join(words)
        f.move(dataset, new_dataset)

    f.close()

    basename = os.path.basename(path)
    dirname = os.path.dirname(path)

    basename_new = basename.replace('+', 'c')
    path_new = os.path.join(dirname, basename_new)

    shutil.move(path, path_new)


def handle_conf(path):
    with open(path, 'r') as f:
        lines = list(f)

    for i, line in enumerate(lines):
        if line.startswith('correlator_list'):
            lines[i] = line.replace('+', 'c')

    with open(path, 'w') as f:
        f.write(''.join(lines))


def main():
    options = _parse_args()

    for path in options.file:
        path = os.path.abspath(path)

        basename = os.path.basename(path)
        base, ext = os.path.splitext(basename)
        
        if ext == '.h5':
            handle_h5(path)
        elif ext == '.ini' or ext == '.in':
            handle_conf(path)
        else:
            print('File extension of {} not supported.'.format(path))


def _parse_args():
    '''
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    '''
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('file', nargs='+')
    options = parser.parse_args()

    return options


if __name__ == '__main__':
    main()
